### ISSUE TITLE
[BUG REPORT]: Packager doesn't create DSS record for tif if data not in watershed extents

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#180]
Tested issue on:
- SWE-CORRECTIONS and SERFC QPE
- Watershed: MVP "Eau Galla River"

**Comment by adamscarberry** [comment]
*****
cumulus-api-packager-1    | Unable to process: castle-data-develop/cumulus/products/nohrsc-snodas-swe-corrections/ssm1054_2022021512.tif
cumulus-api-packager-1    | Traceback (most recent call last):
cumulus-api-packager-1    |   File "/app/packager/writers/dss7.py", line 86, in writer
cumulus-api-packager-1    |     fid.put_grid(
cumulus-api-packager-1    |   File "/usr/local/lib/python3.8/dist-packages/pydsstools/heclib/dss/HecDss.py", line 467, in put_grid
cumulus-api-packager-1    |     stats = computeGridStats(data,compute_range)
cumulus-api-packager-1    |   File "/usr/local/lib/python3.8/dist-packages/pydsstools/heclib/utils.py", line 117, in computeGridStats
cumulus-api-packager-1    |     min_value = data.min()
cumulus-api-packager-1    |   File "/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py", line 44, in _amin
cumulus-api-packager-1    |     return umr_minimum(a, axis, None, out, keepdims, initial, where)
cumulus-api-packager-1    | ValueError: zero-size array to reduction operation minimum which has no identity
cumulus-api-packager-1    | None
cumulus-api-packager-1    | *****

**Comment by adamscarberry** [comment]
Stats are being computed against numpy array, even when all values are np.nan (no value).  The condition can happen when a watershed is selected and no grid coverage is available.

https://github.com/USACE/pydsstools/blob/439cd0e03494b24e2045416eb463b6792ccba0f6/pydsstools/heclib/utils.py#L117    

min_value = data.min()
    max_value = data.max()
    mean_value = data.mean()

**Comment by adamscarberry** [comment]
resolved
